export interface WordData {
  word: string;
  phonetic: string;
  definitions: Array<{
    pos: string;
    meaning: string;
    examples: Array<{ en: string; zh: string }>;
  }>;
}

export const cet6Words: WordData[] = [
  { word: 'abnormal', phonetic: '/æbˈnɔːrml/', definitions: [{ pos: 'adj.', meaning: '不正常的；反常的', examples: [{ en: 'The abnormal weather worried the farmers.', zh: '反常的天气让农民们担忧。' }] }] },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', definitions: [{ pos: 'v.', meaning: '废除；废止', examples: [{ en: 'The government abolished the old tax law.', zh: '政府废除了旧税法。' }] }] },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', definitions: [{ pos: 'adj.', meaning: '突然的；唐突的', examples: [{ en: 'The meeting came to an abrupt end.', zh: '会议突然结束了。' }] }] },
  { word: 'absurd', phonetic: '/əbˈsɜːrd/', definitions: [{ pos: 'adj.', meaning: '荒谬的；可笑的', examples: [{ en: 'The idea seemed absurd at first.', zh: '这个想法起初看起来很荒谬。' }] }] },
  { word: 'abundance', phonetic: '/əˈbʌndəns/', definitions: [{ pos: 'n.', meaning: '丰富；充裕', examples: [{ en: 'The region has an abundance of natural resources.', zh: '该地区自然资源丰富。' }] }] },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', definitions: [{ pos: 'v.', meaning: '容纳；适应', examples: [{ en: 'The hotel can accommodate 500 guests.', zh: '这家酒店可以容纳500位客人。' }] }] },
  { word: 'addict', phonetic: '/ˈædɪkt/', definitions: [{ pos: 'v.', meaning: '使上瘾', examples: [{ en: 'Many teenagers are addicted to social media.', zh: '许多青少年对社交媒体上瘾。' }] }] },
  { word: 'adhere', phonetic: '/ədˈhɪər/', definitions: [{ pos: 'v.', meaning: '坚持；粘附', examples: [{ en: 'We must adhere to the original plan.', zh: '我们必须坚持原计划。' }] }] },
  { word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', definitions: [{ pos: 'adj.', meaning: '邻近的；毗连的', examples: [{ en: 'The two buildings are adjacent to each other.', zh: '两栋建筑彼此相邻。' }] }] },
  { word: 'adversity', phonetic: '/ədˈvɜːrsəti/', definitions: [{ pos: 'n.', meaning: '逆境；不幸', examples: [{ en: 'She showed great courage in adversity.', zh: '她在逆境中表现出了巨大的勇气。' }] }] },
  { word: 'aesthetic', phonetic: '/iːsˈθetɪk/', definitions: [{ pos: 'adj.', meaning: '美学的；审美的', examples: [{ en: 'The building has great aesthetic appeal.', zh: '这座建筑具有极大的美学吸引力。' }] }] },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', definitions: [{ pos: 'v.', meaning: '使隶属；附属', examples: [{ en: 'The hospital is affiliated with the university.', zh: '这家医院隶属于该大学。' }] }] },
  { word: 'aggravate', phonetic: '/ˈæɡrəveɪt/', definitions: [{ pos: 'v.', meaning: '加重；使恶化', examples: [{ en: 'Stress can aggravate health problems.', zh: '压力会加重健康问题。' }] }] },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', definitions: [{ pos: 'v.', meaning: '减轻；缓解', examples: [{ en: 'Medicine can alleviate the pain.', zh: '药物可以缓解疼痛。' }] }] },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', definitions: [{ pos: 'adj.', meaning: '模棱两可的', examples: [{ en: 'The statement was deliberately ambiguous.', zh: '该声明故意模棱两可。' }] }] },
  { word: 'anonymous', phonetic: '/əˈnɒnɪməs/', definitions: [{ pos: 'adj.', meaning: '匿名的', examples: [{ en: 'The donation was made by an anonymous donor.', zh: '这笔捐款来自一位匿名捐赠者。' }] }] },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', definitions: [{ pos: 'v.', meaning: '预期；期望', examples: [{ en: 'We anticipate that sales will increase.', zh: '我们预期销售额会增长。' }] }] },
  { word: 'apparatus', phonetic: '/ˌæpəˈreɪtəs/', definitions: [{ pos: 'n.', meaning: '器械；装置', examples: [{ en: 'The lab is equipped with modern apparatus.', zh: '实验室配备了现代化器械。' }] }] },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtrəri/', definitions: [{ pos: 'adj.', meaning: '任意的；武断的', examples: [{ en: 'The decision seemed arbitrary and unfair.', zh: '这个决定似乎武断且不公平。' }] }] },
  { word: 'authentic', phonetic: '/ɔːˈθentɪk/', definitions: [{ pos: 'adj.', meaning: '真实的；正宗的', examples: [{ en: 'This is an authentic Italian restaurant.', zh: '这是一家正宗的意大利餐厅。' }] }] },
  { word: 'autonomous', phonetic: '/ɔːˈtɒnəməs/', definitions: [{ pos: 'adj.', meaning: '自治的；自主的', examples: [{ en: 'The region is fully autonomous.', zh: '该地区完全自治。' }] }] },
  { word: 'baffle', phonetic: '/ˈbæfl/', definitions: [{ pos: 'v.', meaning: '使困惑；使迷惑', examples: [{ en: 'The problem baffled the scientists.', zh: '这个问题让科学家们困惑不解。' }] }] },
  { word: 'benign', phonetic: '/bɪˈnaɪn/', definitions: [{ pos: 'adj.', meaning: '良性的；温和的', examples: [{ en: 'The tumor was found to be benign.', zh: '肿瘤被发现是良性的。' }] }] },
  { word: 'breach', phonetic: '/briːtʃ/', definitions: [{ pos: 'n.', meaning: '违反；缺口', examples: [{ en: 'This constitutes a breach of contract.', zh: '这构成了违约。' }] }] },
  { word: 'bureaucracy', phonetic: '/bjʊˈrɒkrəsi/', definitions: [{ pos: 'n.', meaning: '官僚主义；官僚体制', examples: [{ en: 'Excessive bureaucracy slows down progress.', zh: '过度的官僚主义阻碍了进步。' }] }] },
  { word: 'catastrophe', phonetic: '/kəˈtæstrəfi/', definitions: [{ pos: 'n.', meaning: '灾难；大祸', examples: [{ en: 'The earthquake was a major catastrophe.', zh: '地震是一场重大灾难。' }] }] },
  { word: 'chronic', phonetic: '/ˈkrɒnɪk/', definitions: [{ pos: 'adj.', meaning: '慢性的；长期的', examples: [{ en: 'Chronic stress can harm your health.', zh: '慢性压力会损害健康。' }] }] },
  { word: 'coherent', phonetic: '/kəʊˈhɪərənt/', definitions: [{ pos: 'adj.', meaning: '连贯的；一致的', examples: [{ en: 'She gave a coherent account of the incident.', zh: '她对事件做了连贯的描述。' }] }] },
  { word: 'compatible', phonetic: '/kəmˈpætəbl/', definitions: [{ pos: 'adj.', meaning: '兼容的；相容的', examples: [{ en: 'The software is compatible with all devices.', zh: '该软件与所有设备兼容。' }] }] },
  { word: 'conceive', phonetic: '/kənˈsiːv/', definitions: [{ pos: 'v.', meaning: '构想；设想', examples: [{ en: 'He conceived the idea during a walk.', zh: '他在散步时产生了这个想法。' }] }] },
  { word: 'contempt', phonetic: '/kənˈtempt/', definitions: [{ pos: 'n.', meaning: '蔑视；鄙视', examples: [{ en: 'He showed contempt for the rules.', zh: '他对规则表示蔑视。' }] }] },
  { word: 'controversy', phonetic: '/ˈkɒntrəvɜːrsi/', definitions: [{ pos: 'n.', meaning: '争议；论战', examples: [{ en: 'The decision sparked a lot of controversy.', zh: '这个决定引发了很多争议。' }] }] },
  { word: 'correlate', phonetic: '/ˈkɒrəleɪt/', definitions: [{ pos: 'v.', meaning: '相关；关联', examples: [{ en: 'Poverty correlates with poor health.', zh: '贫困与健康状况差相关。' }] }] },
  { word: 'corroborate', phonetic: '/kəˈrɒbəreɪt/', definitions: [{ pos: 'v.', meaning: '证实；确认', examples: [{ en: 'New evidence corroborates the theory.', zh: '新证据证实了该理论。' }] }] },
  { word: 'deficiency', phonetic: '/dɪˈfɪʃnsi/', definitions: [{ pos: 'n.', meaning: '缺乏；不足', examples: [{ en: 'Vitamin D deficiency is common in winter.', zh: '冬季维生素D缺乏很常见。' }] }] },
  { word: 'delegate', phonetic: '/ˈdelɪɡeɪt/', definitions: [{ pos: 'v.', meaning: '委派；授权', examples: [{ en: 'A good manager delegates tasks effectively.', zh: '好的管理者能有效委派任务。' }] }] },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', definitions: [{ pos: 'adj.', meaning: '故意的；深思熟虑的', examples: [{ en: 'It was a deliberate attempt to mislead.', zh: '这是故意误导的企图。' }] }] },
  { word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', definitions: [{ pos: 'v.', meaning: '恶化；变坏', examples: [{ en: 'His health has deteriorated rapidly.', zh: '他的健康状况迅速恶化。' }] }] },
  { word: 'dilemma', phonetic: '/dɪˈlemə/', definitions: [{ pos: 'n.', meaning: '困境；两难', examples: [{ en: 'She faced a moral dilemma.', zh: '她面临道德两难。' }] }] },
  { word: 'discourse', phonetic: '/ˈdɪskɔːrs/', definitions: [{ pos: 'n.', meaning: '论述；话语', examples: [{ en: 'The discourse on climate change continues.', zh: '关于气候变化的论述仍在继续。' }] }] },
  { word: 'discretion', phonetic: '/dɪˈskreʃn/', definitions: [{ pos: 'n.', meaning: '谨慎；自由裁量权', examples: [{ en: 'Use your discretion in this matter.', zh: '这件事由你自行斟酌。' }] }] },
  { word: 'displace', phonetic: '/dɪsˈpleɪs/', definitions: [{ pos: 'v.', meaning: '取代；使离开', examples: [{ en: 'Technology has displaced many traditional jobs.', zh: '技术取代了许多传统工作。' }] }] },
  { word: 'disposition', phonetic: '/ˌdɪspəˈzɪʃn/', definitions: [{ pos: 'n.', meaning: '性情；倾向', examples: [{ en: 'She has a cheerful disposition.', zh: '她性格开朗。' }] }] },
  { word: 'disseminate', phonetic: '/dɪˈsemɪneɪt/', definitions: [{ pos: 'v.', meaning: '传播；散布', examples: [{ en: 'The internet disseminates information rapidly.', zh: '互联网快速传播信息。' }] }] },
  { word: 'eloquent', phonetic: '/ˈeləkwənt/', definitions: [{ pos: 'adj.', meaning: '雄辩的；有说服力的', examples: [{ en: 'She gave an eloquent speech.', zh: '她发表了一篇雄辩的演讲。' }] }] },
  { word: 'empirical', phonetic: '/ɪmˈpɪrɪkl/', definitions: [{ pos: 'adj.', meaning: '经验的；实证的', examples: [{ en: 'The study is based on empirical evidence.', zh: '该研究基于实证证据。' }] }] },
  { word: 'encompass', phonetic: '/ɪnˈkʌmpəs/', definitions: [{ pos: 'v.', meaning: '包含；围绕', examples: [{ en: 'The course encompasses many topics.', zh: '该课程包含许多主题。' }] }] },
  { word: 'endeavor', phonetic: '/ɪnˈdevər/', definitions: [{ pos: 'n.', meaning: '努力；尝试', examples: [{ en: 'We must endeavor to improve the situation.', zh: '我们必须努力改善局势。' }] }] },
  { word: 'epidemic', phonetic: '/ˌepɪˈdemɪk/', definitions: [{ pos: 'n.', meaning: '流行病；流行', examples: [{ en: 'The flu epidemic spread quickly.', zh: '流感疫情迅速蔓延。' }] }] },
  { word: 'erosion', phonetic: '/ɪˈrəʊʒn/', definitions: [{ pos: 'n.', meaning: '侵蚀；腐蚀', examples: [{ en: 'Soil erosion is a serious environmental issue.', zh: '土壤侵蚀是一个严重的环境问题。' }] }] },
  { word: 'ethical', phonetic: '/ˈeθɪkl/', definitions: [{ pos: 'adj.', meaning: '伦理的；道德的', examples: [{ en: 'The experiment raised ethical concerns.', zh: '实验引起了伦理方面的担忧。' }] }] },
  { word: 'evacuate', phonetic: '/ɪˈvækjueɪt/', definitions: [{ pos: 'v.', meaning: '疏散；撤离', examples: [{ en: 'Residents were evacuated before the storm.', zh: '居民在暴风雨前被疏散。' }] }] },
  { word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', definitions: [{ pos: 'v.', meaning: '夸大；夸张', examples: [{ en: 'Don\'t exaggerate the difficulty.', zh: '不要夸大困难。' }] }] },
  { word: 'exemplify', phonetic: '/ɪɡˈzemplɪfaɪ/', definitions: [{ pos: 'v.', meaning: '例证；作为榜样', examples: [{ en: 'This case exemplifies the problem.', zh: '这个案例说明了问题。' }] }] },
  { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', definitions: [{ pos: 'v.', meaning: '波动；变动', examples: [{ en: 'Oil prices fluctuate constantly.', zh: '油价不断波动。' }] }] },
  { word: 'formidable', phonetic: '/ˈfɔːrmɪdəbl/', definitions: [{ pos: 'adj.', meaning: '可怕的；强大的', examples: [{ en: 'They face formidable challenges.', zh: '他们面临着可怕的挑战。' }] }] },
  { word: 'formulate', phonetic: '/ˈfɔːrmjuleɪt/', definitions: [{ pos: 'v.', meaning: '制定；构想', examples: [{ en: 'Researchers formulate hypotheses.', zh: '研究人员制定假设。' }] }] },
  { word: 'gloomy', phonetic: '/ˈɡluːmi/', definitions: [{ pos: 'adj.', meaning: '忧郁的；阴暗的', examples: [{ en: 'The economic outlook is gloomy.', zh: '经济前景黯淡。' }] }] },
  { word: 'gratitude', phonetic: '/ˈɡrætɪtjuːd/', definitions: [{ pos: 'n.', meaning: '感激；感恩', examples: [{ en: 'She expressed her gratitude sincerely.', zh: '她真诚地表达了感激之情。' }] }] },
  { word: 'hierarchy', phonetic: '/ˈhaɪərɑːrki/', definitions: [{ pos: 'n.', meaning: '等级制度；层级', examples: [{ en: 'There is a strict hierarchy in the organization.', zh: '组织中有严格的等级制度。' }] }] },
  { word: 'hypothesis', phonetic: '/haɪˈpɒθəsɪs/', definitions: [{ pos: 'n.', meaning: '假设；假说', examples: [{ en: 'Scientists proposed a new hypothesis.', zh: '科学家提出了新假设。' }] }] },
  { word: 'illuminate', phonetic: '/ɪˈluːmɪneɪt/', definitions: [{ pos: 'v.', meaning: '阐明；照亮', examples: [{ en: 'The report illuminates the key issues.', zh: '报告阐明了关键问题。' }] }] },
  { word: 'immense', phonetic: '/ɪˈmens/', definitions: [{ pos: 'adj.', meaning: '巨大的；广大的', examples: [{ en: 'The project requires immense effort.', zh: '项目需要巨大努力。' }] }] },
  { word: 'imperative', phonetic: '/ɪmˈperətɪv/', definitions: [{ pos: 'adj.', meaning: '迫切的；必要的', examples: [{ en: 'It is imperative that we act now.', zh: '我们现在必须行动。' }] }] },
  { word: 'implicit', phonetic: '/ɪmˈplɪsɪt/', definitions: [{ pos: 'adj.', meaning: '含蓄的；隐含的', examples: [{ en: 'There was an implicit warning in his words.', zh: '他的话中有隐含的警告。' }] }] },
  { word: 'impulse', phonetic: '/ˈɪmpʌls/', definitions: [{ pos: 'n.', meaning: '冲动；脉冲', examples: [{ en: 'She bought the dress on impulse.', zh: '她一时冲动买了裙子。' }] }] },
  { word: 'incentive', phonetic: '/ɪnˈsentɪv/', definitions: [{ pos: 'n.', meaning: '激励；动机', examples: [{ en: 'Tax breaks provide an incentive for investment.', zh: '税收减免为投资提供了激励。' }] }] },
  { word: 'incidence', phonetic: '/ˈɪnsɪdəns/', definitions: [{ pos: 'n.', meaning: '发生率；影响', examples: [{ en: 'The incidence of the disease has decreased.', zh: '该疾病的发生率下降了。' }] }] },
  { word: 'incur', phonetic: '/ɪnˈkɜːr/', definitions: [{ pos: 'v.', meaning: '招致；引起', examples: [{ en: 'He incurred heavy debts.', zh: '他背负了沉重的债务。' }] }] },
  { word: 'indigenous', phonetic: '/ɪnˈdɪdʒənəs/', definitions: [{ pos: 'adj.', meaning: '本土的；土著的', examples: [{ en: 'Indigenous cultures should be preserved.', zh: '本土文化应该被保护。' }] }] },
  { word: 'indispensable', phonetic: '/ˌɪndɪˈspensəbl/', definitions: [{ pos: 'adj.', meaning: '不可缺少的', examples: [{ en: 'Water is indispensable for life.', zh: '水是生命不可缺少的。' }] }] },
  { word: 'influx', phonetic: '/ˈɪnflʌks/', definitions: [{ pos: 'n.', meaning: '涌入；流入', examples: [{ en: 'The city experienced an influx of tourists.', zh: '城市经历了游客的涌入。' }] }] },
  { word: 'infrastructure', phonetic: '/ˈɪnfrəstrʌktʃər/', definitions: [{ pos: 'n.', meaning: '基础设施', examples: [{ en: 'The country needs better infrastructure.', zh: '国家需要更好的基础设施。' }] }] },
  { word: 'inherent', phonetic: '/ɪnˈhɪərənt/', definitions: [{ pos: 'adj.', meaning: '固有的；内在的', examples: [{ en: 'There are inherent risks in any investment.', zh: '任何投资都有固有风险。' }] }] },
  { word: 'innovative', phonetic: '/ˈɪnəveɪtɪv/', definitions: [{ pos: 'adj.', meaning: '创新的', examples: [{ en: 'The company is known for its innovative products.', zh: '公司以创新产品闻名。' }] }] },
  { word: 'integrity', phonetic: '/ɪnˈteɡrəti/', definitions: [{ pos: 'n.', meaning: '正直；完整', examples: [{ en: 'He is a man of great integrity.', zh: '他是一个非常正直的人。' }] }] },
  { word: 'intensify', phonetic: '/ɪnˈtensɪfaɪ/', definitions: [{ pos: 'v.', meaning: '加强；加剧', examples: [{ en: 'The conflict has intensified.', zh: '冲突加剧了。' }] }] },
  { word: 'intricate', phonetic: '/ˈɪntrɪkət/', definitions: [{ pos: 'adj.', meaning: '复杂的；精细的', examples: [{ en: 'The design is intricate and beautiful.', zh: '设计复杂而精美。' }] }] },
  { word: 'jurisdiction', phonetic: '/ˌdʒʊərɪsˈdɪkʃn/', definitions: [{ pos: 'n.', meaning: '管辖权；司法权', examples: [{ en: 'This matter falls under our jurisdiction.', zh: '此事属于我们的管辖范围。' }] }] },
  { word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', definitions: [{ pos: 'adj.', meaning: '合法的；正当的', examples: [{ en: 'He has a legitimate claim to the property.', zh: '他对该财产有合法的权利。' }] }] },
  { word: 'mandatory', phonetic: '/ˈmændətɔːri/', definitions: [{ pos: 'adj.', meaning: '强制的；法定的', examples: [{ en: 'Wearing seatbelts is mandatory.', zh: '系安全带是强制性的。' }] }] },
  { word: 'methodology', phonetic: '/ˌmeθəˈdɒlədʒi/', definitions: [{ pos: 'n.', meaning: '方法论', examples: [{ en: 'The research uses sound methodology.', zh: '研究使用了可靠的方法论。' }] }] },
  { word: 'municipal', phonetic: '/mjuːˈnɪsɪpl/', definitions: [{ pos: 'adj.', meaning: '市政的；地方的', examples: [{ en: 'The municipal government approved the plan.', zh: '市政府批准了该计划。' }] }] },
  { word: 'negligible', phonetic: '/ˈneɡlɪdʒəbl/', definitions: [{ pos: 'adj.', meaning: '微不足道的', examples: [{ en: 'The impact on the environment is negligible.', zh: '对环境的影响微不足道。' }] }] },
  { word: 'norm', phonetic: '/nɔːrm/', definitions: [{ pos: 'n.', meaning: '规范；标准', examples: [{ en: 'This behavior is not the social norm.', zh: '这种行为不是社会规范。' }] }] },
  { word: 'obsolete', phonetic: '/ˈɒbsəliːt/', definitions: [{ pos: 'adj.', meaning: '过时的；废弃的', examples: [{ en: 'The technology has become obsolete.', zh: '这项技术已经过时了。' }] }] },
  { word: 'paradigm', phonetic: '/ˈpærədaɪm/', definitions: [{ pos: 'n.', meaning: '范式；典范', examples: [{ en: 'The internet created a new paradigm for communication.', zh: '互联网创造了新的沟通范式。' }] }] },
  { word: 'paradox', phonetic: '/ˈpærədɒks/', definitions: [{ pos: 'n.', meaning: '悖论；矛盾', examples: [{ en: 'It is a paradox that the busiest people often find the most time.', zh: '最忙的人往往最有时间，这是一个悖论。' }] }] },
  { word: 'perpetual', phonetic: '/pərˈpetʃuəl/', definitions: [{ pos: 'adj.', meaning: '永久的；不断的', examples: [{ en: 'The city is in a state of perpetual motion.', zh: '这座城市永远在运动中。' }] }] },
  { word: 'plausible', phonetic: '/ˈplɔːzəbl/', definitions: [{ pos: 'adj.', meaning: '似乎合理的', examples: [{ en: 'His explanation sounds plausible.', zh: '他的解释听起来似乎合理。' }] }] },
  { word: 'prevalent', phonetic: '/ˈprevələnt/', definitions: [{ pos: 'adj.', meaning: '流行的；普遍的', examples: [{ en: 'The disease is prevalent in tropical regions.', zh: '这种疾病在热带地区很普遍。' }] }] },
  { word: 'profound', phonetic: '/prəˈfaʊnd/', definitions: [{ pos: 'adj.', meaning: '深刻的；深远的', examples: [{ en: 'The book had a profound impact on me.', zh: '这本书对我产生了深远影响。' }] }] },
  { word: 'propagate', phonetic: '/ˈprɒpəɡeɪt/', definitions: [{ pos: 'v.', meaning: '传播；繁殖', examples: [{ en: 'The organization propagates its ideas through media.', zh: '该组织通过媒体传播其理念。' }] }] },
  { word: 'ratify', phonetic: '/ˈrætɪfaɪ/', definitions: [{ pos: 'v.', meaning: '批准；认可', examples: [{ en: 'The treaty was ratified by the senate.', zh: '条约被参议院批准。' }] }] },
  { word: 'resilient', phonetic: '/rɪˈzɪliənt/', definitions: [{ pos: 'adj.', meaning: '有弹性的；适应力强的', examples: [{ en: 'Children are often very resilient.', zh: '孩子们通常适应力很强。' }] }] },
  { word: 'retrospect', phonetic: '/ˈretrəspekt/', definitions: [{ pos: 'n.', meaning: '回顾', examples: [{ en: 'In retrospect, the decision was correct.', zh: '回想起来，那个决定是正确的。' }] }] },
  { word: 'scrutiny', phonetic: '/ˈskruːtəni/', definitions: [{ pos: 'n.', meaning: '仔细检查；审查', examples: [{ en: 'The proposal came under close scrutiny.', zh: '提案受到了严格审查。' }] }] },
  { word: 'simultaneous', phonetic: '/ˌsɪmlˈteɪniəs/', definitions: [{ pos: 'adj.', meaning: '同时的', examples: [{ en: 'The event was broadcast with simultaneous translation.', zh: '活动进行了同声传译。' }] }] },
  { word: 'skeptical', phonetic: '/ˈskeptɪkl/', definitions: [{ pos: 'adj.', meaning: '怀疑的', examples: [{ en: 'Scientists are skeptical about the claim.', zh: '科学家们对这个说法持怀疑态度。' }] }] },
  { word: 'speculate', phonetic: '/ˈspekjuleɪt/', definitions: [{ pos: 'v.', meaning: '推测；投机', examples: [{ en: 'Analysts speculate about the market trend.', zh: '分析师们推测市场趋势。' }] }] },
  { word: 'subordinate', phonetic: '/səˈbɔːrdɪnət/', definitions: [{ pos: 'adj.', meaning: '下级的；次要的', examples: [{ en: 'He was subordinate to the director.', zh: '他隶属于主任。' }] }] },
  { word: 'subsequent', phonetic: '/ˈsʌbsɪkwənt/', definitions: [{ pos: 'adj.', meaning: '随后的；后来的', examples: [{ en: 'Subsequent events proved him right.', zh: '后来的事件证明他是对的。' }] }] },
  { word: 'subsidiary', phonetic: '/səbˈsɪdiəri/', definitions: [{ pos: 'n.', meaning: '子公司；附属机构', examples: [{ en: 'The company has subsidiaries in 20 countries.', zh: '公司在20个国家有子公司。' }] }] },
  { word: 'supplementary', phonetic: '/ˌsʌplɪˈmentri/', definitions: [{ pos: 'adj.', meaning: '补充的；附加的', examples: [{ en: 'The textbook comes with supplementary materials.', zh: '教材附有补充材料。' }] }] },
  { word: 'surveillance', phonetic: '/sɜːrˈveɪləns/', definitions: [{ pos: 'n.', meaning: '监视；监控', examples: [{ en: 'The area is under constant surveillance.', zh: '该区域处于持续监控之下。' }] }] },
  { word: 'tangible', phonetic: '/ˈtændʒəbl/', definitions: [{ pos: 'adj.', meaning: '有形的；切实的', examples: [{ en: 'We need tangible evidence.', zh: '我们需要切实的证据。' }] }] },
  { word: 'terminate', phonetic: '/ˈtɜːrmɪneɪt/', definitions: [{ pos: 'v.', meaning: '终止；结束', examples: [{ en: 'The contract was terminated early.', zh: '合同提前终止了。' }] }] },
  { word: 'threshold', phonetic: '/ˈθreʃhəʊld/', definitions: [{ pos: 'n.', meaning: '门槛；起点', examples: [{ en: 'We are on the threshold of a new era.', zh: '我们正处于新时代的起点。' }] }] },
  { word: 'unanimous', phonetic: '/juˈnænɪməs/', definitions: [{ pos: 'adj.', meaning: '全体一致的', examples: [{ en: 'The decision was unanimous.', zh: '决定是一致通过的。' }] }] },
  { word: 'underlying', phonetic: '/ˌʌndərˈlaɪɪŋ/', definitions: [{ pos: 'adj.', meaning: '潜在的；根本的', examples: [{ en: 'The underlying cause of the problem is poverty.', zh: '问题的根本原因是贫困。' }] }] },
  { word: 'validate', phonetic: '/ˈvælɪdeɪt/', definitions: [{ pos: 'v.', meaning: '验证；确认', examples: [{ en: 'Further research is needed to validate the findings.', zh: '需要进一步研究来验证这些发现。' }] }] },
  { word: 'variable', phonetic: '/ˈveəriəbl/', definitions: [{ pos: 'n.', meaning: '变量', examples: [{ en: 'There are too many variables to consider.', zh: '需要考虑的变量太多了。' }] }] },
  { word: 'versatile', phonetic: '/ˈvɜːrsətaɪl/', definitions: [{ pos: 'adj.', meaning: '多才多艺的；通用的', examples: [{ en: 'She is a versatile performer.', zh: '她是一位多才多艺的表演者。' }] }] },
  { word: 'volatile', phonetic: '/ˈvɒlətaɪl/', definitions: [{ pos: 'adj.', meaning: '易变的；不稳定的', examples: [{ en: 'The stock market has been volatile recently.', zh: '股市最近波动很大。' }] }] },
  { word: 'vulnerable', phonetic: '/ˈvʌlnərəbl/', definitions: [{ pos: 'adj.', meaning: '脆弱的；易受伤的', examples: [{ en: 'Elderly people are more vulnerable to infections.', zh: '老年人更容易感染。' }] }] },
  { word: 'warrant', phonetic: '/ˈwɒrənt/', definitions: [{ pos: 'v.', meaning: '保证；授权', examples: [{ en: 'The situation warrants immediate attention.', zh: '这种情况需要立即关注。' }] }] },
  { word: 'withhold', phonetic: '/wɪðˈhəʊld/', definitions: [{ pos: 'v.', meaning: '保留；隐瞒', examples: [{ en: 'The company withheld the information.', zh: '公司隐瞒了信息。' }] }] },
];

export const ieltsWords: WordData[] = [
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', definitions: [{ pos: 'v.', meaning: '容纳；提供住宿', examples: [{ en: 'The hotel can accommodate up to 200 guests.', zh: '酒店最多可容纳200位客人。' }] }] },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', definitions: [{ pos: 'v.', meaning: '承认；确认', examples: [{ en: 'The government acknowledged the problem.', zh: '政府承认了这个问题。' }] }] },
  { word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', definitions: [{ pos: 'n.', meaning: '获取；收购', examples: [{ en: 'Language acquisition is easier for children.', zh: '儿童更容易习得语言。' }] }] },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', definitions: [{ pos: 'adj.', meaning: '足够的；适当的', examples: [{ en: 'The funding is not adequate for the project.', zh: '资金不足以完成项目。' }] }] },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', definitions: [{ pos: 'v.', meaning: '提倡；主张', examples: [{ en: 'She advocates for equal rights.', zh: '她提倡平等权利。' }] }] },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', definitions: [{ pos: 'v.', meaning: '使隶属；关联', examples: [{ en: 'The college is affiliated with the university.', zh: '该学院隶属于这所大学。' }] }] },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', definitions: [{ pos: 'v.', meaning: '分配；拨出', examples: [{ en: 'The government allocated funds for education.', zh: '政府拨出了教育资金。' }] }] },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', definitions: [{ pos: 'n.', meaning: '替代选择', examples: [{ en: 'We need to find alternative energy sources.', zh: '我们需要找到替代能源。' }] }] },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', definitions: [{ pos: 'adj.', meaning: '模棱两可的', examples: [{ en: 'The instructions were ambiguous.', zh: '说明含糊不清。' }] }] },
  { word: 'analogy', phonetic: '/əˈnælədʒi/', definitions: [{ pos: 'n.', meaning: '类比；类推', examples: [{ en: 'He drew an analogy between life and a journey.', zh: '他把人生比作旅途。' }] }] },
  { word: 'apparent', phonetic: '/əˈpærənt/', definitions: [{ pos: 'adj.', meaning: '明显的；表面上的', examples: [{ en: 'The difference was apparent to everyone.', zh: '差异对每个人来说都是明显的。' }] }] },
  { word: 'approximately', phonetic: '/əˈprɒksɪmətli/', definitions: [{ pos: 'adv.', meaning: '大约；近似地', examples: [{ en: 'The journey takes approximately three hours.', zh: '旅程大约需要三个小时。' }] }] },
  { word: 'assess', phonetic: '/əˈses/', definitions: [{ pos: 'v.', meaning: '评估；评价', examples: [{ en: 'We need to assess the impact of the policy.', zh: '我们需要评估政策的影响。' }] }] },
  { word: 'assumption', phonetic: '/əˈsʌmpʃn/', definitions: [{ pos: 'n.', meaning: '假设；假定', examples: [{ en: 'The theory is based on several assumptions.', zh: '该理论基于几个假设。' }] }] },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', definitions: [{ pos: 'v.', meaning: '归因于', examples: [{ en: 'She attributes her success to hard work.', zh: '她把成功归因于努力工作。' }] }] },
  { word: 'bias', phonetic: '/ˈbaɪəs/', definitions: [{ pos: 'n.', meaning: '偏见；偏差', examples: [{ en: 'The report showed a clear bias.', zh: '报告显示了明显的偏见。' }] }] },
  { word: 'catalogue', phonetic: '/ˈkætəlɒɡ/', definitions: [{ pos: 'n.', meaning: '目录；一览表', examples: [{ en: 'The library has an online catalogue.', zh: '图书馆有在线目录。' }] }] },
  { word: 'cite', phonetic: '/saɪt/', definitions: [{ pos: 'v.', meaning: '引用；引证', examples: [{ en: 'The author cited several studies.', zh: '作者引用了几项研究。' }] }] },
  { word: 'coherent', phonetic: '/kəʊˈhɪərənt/', definitions: [{ pos: 'adj.', meaning: '连贯的；一致的', examples: [{ en: 'He presented a coherent argument.', zh: '他提出了连贯的论点。' }] }] },
  { word: 'coincide', phonetic: '/ˌkəʊɪnˈsaɪd/', definitions: [{ pos: 'v.', meaning: '同时发生；一致', examples: [{ en: 'The two events coincided.', zh: '两个事件同时发生了。' }] }] },
  { word: 'commodity', phonetic: '/kəˈmɒdəti/', definitions: [{ pos: 'n.', meaning: '商品；日用品', examples: [{ en: 'Oil is an important commodity.', zh: '石油是重要的商品。' }] }] },
  { word: 'compatible', phonetic: '/kəmˈpætəbl/', definitions: [{ pos: 'adj.', meaning: '兼容的；相容的', examples: [{ en: 'The two systems are compatible.', zh: '两个系统是兼容的。' }] }] },
  { word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', definitions: [{ pos: 'v.', meaning: '补偿；赔偿', examples: [{ en: 'The company compensated the victims.', zh: '公司赔偿了受害者。' }] }] },
  { word: 'conceive', phonetic: '/kənˈsiːv/', definitions: [{ pos: 'v.', meaning: '构想；设想', examples: [{ en: 'It is difficult to conceive of a solution.', zh: '很难想出一个解决方案。' }] }] },
  { word: 'conclusive', phonetic: '/kənˈkluːsɪv/', definitions: [{ pos: 'adj.', meaning: '决定性的；确凿的', examples: [{ en: 'There is no conclusive evidence.', zh: '没有确凿的证据。' }] }] },
  { word: 'consensus', phonetic: '/kənˈsensəs/', definitions: [{ pos: 'n.', meaning: '共识；一致', examples: [{ en: 'The committee reached a consensus.', zh: '委员会达成了共识。' }] }] },
  { word: 'consolidate', phonetic: '/kənˈsɒlɪdeɪt/', definitions: [{ pos: 'v.', meaning: '巩固；合并', examples: [{ en: 'The company consolidated its market position.', zh: '公司巩固了市场地位。' }] }] },
  { word: 'contemplate', phonetic: '/ˈkɒntəmpleɪt/', definitions: [{ pos: 'v.', meaning: '沉思；考虑', examples: [{ en: 'She contemplated changing her career.', zh: '她考虑换职业。' }] }] },
  { word: 'contradict', phonetic: '/ˌkɒntrəˈdɪkt/', definitions: [{ pos: 'v.', meaning: '反驳；矛盾', examples: [{ en: 'The evidence contradicts his statement.', zh: '证据与他的陈述相矛盾。' }] }] },
  { word: 'controversial', phonetic: '/ˌkɒntrəˈvɜːrʃl/', definitions: [{ pos: 'adj.', meaning: '有争议的', examples: [{ en: 'The topic remains controversial.', zh: '这个话题仍然有争议。' }] }] },
  { word: 'conventional', phonetic: '/kənˈvenʃənl/', definitions: [{ pos: 'adj.', meaning: '传统的；常规的', examples: [{ en: 'Conventional methods may not work.', zh: '常规方法可能不起作用。' }] }] },
  { word: 'curriculum', phonetic: '/kəˈrɪkjələm/', definitions: [{ pos: 'n.', meaning: '课程；课程体系', examples: [{ en: 'The school has updated its curriculum.', zh: '学校更新了课程体系。' }] }] },
  { word: 'decline', phonetic: '/dɪˈklaɪn/', definitions: [{ pos: 'v.', meaning: '下降；拒绝', examples: [{ en: 'The population has declined significantly.', zh: '人口大幅下降。' }] }] },
  { word: 'deficiency', phonetic: '/dɪˈfɪʃnsi/', definitions: [{ pos: 'n.', meaning: '缺乏；不足', examples: [{ en: 'Iron deficiency can cause anemia.', zh: '缺铁会导致贫血。' }] }] },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', definitions: [{ pos: 'adj.', meaning: '故意的；深思熟虑的', examples: [{ en: 'It was a deliberate attempt to deceive.', zh: '这是蓄意欺骗。' }] }] },
  { word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', definitions: [{ pos: 'v.', meaning: '恶化；变坏', examples: [{ en: 'Air quality continues to deteriorate.', zh: '空气质量持续恶化。' }] }] },
  { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', definitions: [{ pos: 'v.', meaning: '减少；削弱', examples: [{ en: 'The threat has diminished over time.', zh: '威胁随时间减弱了。' }] }] },
  { word: 'discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃn/', definitions: [{ pos: 'n.', meaning: '歧视；辨别力', examples: [{ en: 'Racial discrimination is illegal.', zh: '种族歧视是违法的。' }] }] },
  { word: 'displace', phonetic: '/dɪsˈpleɪs/', definitions: [{ pos: 'v.', meaning: '取代；使离开', examples: [{ en: 'Thousands were displaced by the flood.', zh: '数千人因洪水而流离失所。' }] }] },
  { word: 'distort', phonetic: '/dɪˈstɔːrt/', definitions: [{ pos: 'v.', meaning: '扭曲；歪曲', examples: [{ en: 'The media distorted the facts.', zh: '媒体歪曲了事实。' }] }] },
  { word: 'diversify', phonetic: '/daɪˈvɜːrsɪfaɪ/', definitions: [{ pos: 'v.', meaning: '使多样化', examples: [{ en: 'The company diversified its product range.', zh: '公司使产品范围多样化。' }] }] },
  { word: 'dominant', phonetic: '/ˈdɒmɪnənt/', definitions: [{ pos: 'adj.', meaning: '占主导地位的', examples: [{ en: 'English is the dominant language in business.', zh: '英语是商业中的主导语言。' }] }] },
  { word: 'elaborate', phonetic: '/ɪˈlæbərət/', definitions: [{ pos: 'adj.', meaning: '精心制作的；详尽的', examples: [{ en: 'She made elaborate preparations.', zh: '她做了精心准备。' }] }] },
  { word: 'endeavor', phonetic: '/ɪnˈdevər/', definitions: [{ pos: 'n.', meaning: '努力；事业', examples: [{ en: 'We should endeavor to succeed.', zh: '我们应该努力成功。' }] }] },
  { word: 'encompass', phonetic: '/ɪnˈkʌmpəs/', definitions: [{ pos: 'v.', meaning: '包含；围绕', examples: [{ en: 'The course encompasses many subjects.', zh: '课程包含许多科目。' }] }] },
  { word: 'epidemic', phonetic: '/ˌepɪˈdemɪk/', definitions: [{ pos: 'n.', meaning: '流行病；流行', examples: [{ en: 'Obesity has become an epidemic.', zh: '肥胖已成为一种流行病。' }] }] },
  { word: 'equivalent', phonetic: '/ɪˈkwɪvələnt/', definitions: [{ pos: 'adj.', meaning: '等价的；相当的', examples: [{ en: 'One dollar is equivalent to about seven yuan.', zh: '一美元大约等于七元人民币。' }] }] },
  { word: 'erode', phonetic: '/ɪˈrəʊd/', definitions: [{ pos: 'v.', meaning: '侵蚀；腐蚀', examples: [{ en: 'Wind and rain eroded the cliff face.', zh: '风雨侵蚀了悬崖表面。' }] }] },
  { word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', definitions: [{ pos: 'v.', meaning: '开发；利用', examples: [{ en: 'We must exploit renewable energy.', zh: '我们必须开发利用可再生能源。' }] }] },
  { word: 'facilitate', phonetic: '/fəˈsɪlɪteɪt/', definitions: [{ pos: 'v.', meaning: '促进；使便利', examples: [{ en: 'Technology facilitates communication.', zh: '技术促进了沟通。' }] }] },
  { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', definitions: [{ pos: 'v.', meaning: '波动；变动', examples: [{ en: 'Prices fluctuate according to demand.', zh: '价格随需求波动。' }] }] },
  { word: 'implement', phonetic: '/ˈɪmplɪment/', definitions: [{ pos: 'v.', meaning: '实施；执行', examples: [{ en: 'The government implemented new policies.', zh: '政府实施了新政策。' }] }] },
  { word: 'incentive', phonetic: '/ɪnˈsentɪv/', definitions: [{ pos: 'n.', meaning: '激励；动机', examples: [{ en: 'Financial incentives encourage productivity.', zh: '经济激励促进生产力。' }] }] },
  { word: 'infrastructure', phonetic: '/ˈɪnfrəstrʌktʃər/', definitions: [{ pos: 'n.', meaning: '基础设施', examples: [{ en: 'Good infrastructure is essential for growth.', zh: '良好的基础设施对增长至关重要。' }] }] },
  { word: 'intervention', phonetic: '/ˌɪntərˈvenʃn/', definitions: [{ pos: 'n.', meaning: '干预；介入', examples: [{ en: 'Military intervention was controversial.', zh: '军事干预引起了争议。' }] }] },
  { word: 'legislation', phonetic: '/ˌledʒɪsˈleɪʃn/', definitions: [{ pos: 'n.', meaning: '立法；法律', examples: [{ en: 'New legislation was introduced last year.', zh: '去年出台了新法律。' }] }] },
  { word: 'migration', phonetic: '/maɪˈɡreɪʃn/', definitions: [{ pos: 'n.', meaning: '迁移；移民', examples: [{ en: 'Bird migration is a natural phenomenon.', zh: '鸟类迁徙是一种自然现象。' }] }] },
  { word: 'obstacle', phonetic: '/ˈɒbstəkl/', definitions: [{ pos: 'n.', meaning: '障碍；阻碍', examples: [{ en: 'Lack of funding is a major obstacle.', zh: '缺乏资金是一个主要障碍。' }] }] },
  { word: 'perceive', phonetic: '/pərˈsiːv/', definitions: [{ pos: 'v.', meaning: '感知；察觉', examples: [{ en: 'She perceived a change in his attitude.', zh: '她察觉到他态度的变化。' }] }] },
  { word: 'phenomenon', phonetic: '/fɪˈnɒmɪnən/', definitions: [{ pos: 'n.', meaning: '现象', examples: [{ en: 'Global warming is a well-documented phenomenon.', zh: '全球变暖是有充分记录的现象。' }] }] },
  { word: 'predominant', phonetic: '/prɪˈdɒmɪnənt/', definitions: [{ pos: 'adj.', meaning: '主要的；占优势的', examples: [{ en: 'Yellow is the predominant color in the painting.', zh: '黄色是画作中的主要颜色。' }] }] },
  { word: 'prospect', phonetic: '/ˈprɒspekt/', definitions: [{ pos: 'n.', meaning: '前景；展望', examples: [{ en: 'The prospects for economic recovery are good.', zh: '经济复苏的前景良好。' }] }] },
  { word: 'remuneration', phonetic: '/rɪˌmjuːnəˈreɪʃn/', definitions: [{ pos: 'n.', meaning: '报酬；薪酬', examples: [{ en: 'The remuneration package is attractive.', zh: '薪酬方案很有吸引力。' }] }] },
  { word: 'sustainable', phonetic: '/səˈsteɪnəbl/', definitions: [{ pos: 'adj.', meaning: '可持续的', examples: [{ en: 'Sustainable development is a global priority.', zh: '可持续发展是全球优先事项。' }] }] },
  { word: 'transition', phonetic: '/trænˈzɪʃn/', definitions: [{ pos: 'n.', meaning: '过渡；转变', examples: [{ en: 'The transition to digital media was gradual.', zh: '向数字媒体的过渡是渐进的。' }] }] },
  { word: 'trend', phonetic: '/trend/', definitions: [{ pos: 'n.', meaning: '趋势；潮流', examples: [{ en: 'There is a growing trend towards remote work.', zh: '远程办公的趋势日益增长。' }] }] },
  { word: 'trigger', phonetic: '/ˈtrɪɡər/', definitions: [{ pos: 'v.', meaning: '触发；引起', examples: [{ en: 'The incident triggered a public debate.', zh: '事件引发了公众讨论。' }] }] },
  { word: 'utilise', phonetic: '/ˈjuːtəlaɪz/', definitions: [{ pos: 'v.', meaning: '利用', examples: [{ en: 'We must utilise all available resources.', zh: '我们必须利用所有可用资源。' }] }] },
  { word: 'widespread', phonetic: '/ˈwaɪdspred/', definitions: [{ pos: 'adj.', meaning: '广泛的；普遍的', examples: [{ en: 'The practice is widespread in many countries.', zh: '这种做法在许多国家很普遍。' }] }] },
];

export const postgraduateWords: WordData[] = [
  { word: 'abide', phonetic: '/əˈbaɪd/', definitions: [{ pos: 'v.', meaning: '遵守；忍受', examples: [{ en: 'You must abide by the rules.', zh: '你必须遵守规则。' }] }] },
  { word: 'abstain', phonetic: '/əbˈsteɪn/', definitions: [{ pos: 'v.', meaning: '弃权；戒除', examples: [{ en: 'He decided to abstain from voting.', zh: '他决定弃权。' }] }] },
  { word: 'affirm', phonetic: '/əˈfɜːrm/', definitions: [{ pos: 'v.', meaning: '断言；肯定', examples: [{ en: 'She affirmed her commitment to the project.', zh: '她肯定了对项目的承诺。' }] }] },
  { word: 'allege', phonetic: '/əˈledʒ/', definitions: [{ pos: 'v.', meaning: '声称；宣称', examples: [{ en: 'He alleged that the company had cheated him.', zh: '他声称公司欺骗了他。' }] }] },
  { word: 'appeal', phonetic: '/əˈpiːl/', definitions: [{ pos: 'v.', meaning: '呼吁；上诉', examples: [{ en: 'They appealed to the public for donations.', zh: '他们向公众呼吁捐款。' }] }] },
  { word: 'ascertain', phonetic: '/ˌæsərˈteɪn/', definitions: [{ pos: 'v.', meaning: '确定；查明', examples: [{ en: 'We need to ascertain the facts first.', zh: '我们需要先查明事实。' }] }] },
  { word: 'ascribe', phonetic: '/əˈskraɪb/', definitions: [{ pos: 'v.', meaning: '归因于', examples: [{ en: 'He ascribed his success to luck.', zh: '他把成功归因于运气。' }] }] },
  { word: 'assimilate', phonetic: '/əˈsɪməleɪt/', definitions: [{ pos: 'v.', meaning: '同化；吸收', examples: [{ en: 'Immigrants gradually assimilate into the culture.', zh: '移民逐渐融入当地文化。' }] }] },
  { word: 'attest', phonetic: '/əˈtest/', definitions: [{ pos: 'v.', meaning: '证明；作证', examples: [{ en: 'The documents attest to his innocence.', zh: '文件证明了他的清白。' }] }] },
  { word: 'augment', phonetic: '/ɔːɡˈment/', definitions: [{ pos: 'v.', meaning: '增加；扩大', examples: [{ en: 'She took a second job to augment her income.', zh: '她做了第二份工作来增加收入。' }] }] },
  { word: 'bolster', phonetic: '/ˈbəʊlstər/', definitions: [{ pos: 'v.', meaning: '支持；增强', examples: [{ en: 'New data bolstered the theory.', zh: '新数据支持了该理论。' }] }] },
  { word: 'circumvent', phonetic: '/ˌsɜːrkəmˈvent/', definitions: [{ pos: 'v.', meaning: '规避；绕过', examples: [{ en: 'They tried to circumvent the regulations.', zh: '他们试图规避规定。' }] }] },
  { word: 'coerce', phonetic: '/kəʊˈɜːrs/', definitions: [{ pos: 'v.', meaning: '强迫；胁迫', examples: [{ en: 'He was coerced into signing the document.', zh: '他被迫签署了文件。' }] }] },
  { word: 'complacent', phonetic: '/kəmˈpleɪsnt/', definitions: [{ pos: 'adj.', meaning: '自满的；得意的', examples: [{ en: 'We must not become complacent about safety.', zh: '我们不能对安全掉以轻心。' }] }] },
  { word: 'concede', phonetic: '/kənˈsiːd/', definitions: [{ pos: 'v.', meaning: '承认；让步', examples: [{ en: 'He conceded defeat in the election.', zh: '他承认在选举中失败。' }] }] },
  { word: 'conceive', phonetic: '/kənˈsiːv/', definitions: [{ pos: 'v.', meaning: '构想；怀孕', examples: [{ en: 'It is hard to conceive of living without water.', zh: '很难想象没有水的生活。' }] }] },
  { word: 'contend', phonetic: '/kənˈtend/', definitions: [{ pos: 'v.', meaning: '竞争；争辩', examples: [{ en: 'She contended that the report was inaccurate.', zh: '她争辩说报告不准确。' }] }] },
  { word: 'contrive', phonetic: '/kənˈtraɪv/', definitions: [{ pos: 'v.', meaning: '设法；策划', examples: [{ en: 'He contrived a way to escape.', zh: '他策划了一种逃跑方式。' }] }] },
  { word: 'corroborate', phonetic: '/kəˈrɒbəreɪt/', definitions: [{ pos: 'v.', meaning: '证实；确认', examples: [{ en: 'Witnesses corroborated his story.', zh: '证人证实了他的说法。' }] }] },
  { word: 'counteract', phonetic: '/ˌkaʊntərˈækt/', definitions: [{ pos: 'v.', meaning: '抵消；对抗', examples: [{ en: 'Exercise can counteract the effects of stress.', zh: '运动可以抵消压力的影响。' }] }] },
  { word: 'curb', phonetic: '/kɜːrb/', definitions: [{ pos: 'v.', meaning: '控制；抑制', examples: [{ en: 'Measures were taken to curb inflation.', zh: '采取了措施来抑制通胀。' }] }] },
  { word: 'debilitate', phonetic: '/dɪˈbɪlɪteɪt/', definitions: [{ pos: 'v.', meaning: '使衰弱', examples: [{ en: 'The illness debilitated him for months.', zh: '疾病使他虚弱了数月。' }] }] },
  { word: 'deplete', phonetic: '/dɪˈpliːt/', definitions: [{ pos: 'v.', meaning: '耗尽；减少', examples: [{ en: 'The reserves have been severely depleted.', zh: '储备已严重耗尽。' }] }] },
  { word: 'depreciate', phonetic: '/dɪˈpriːʃieɪt/', definitions: [{ pos: 'v.', meaning: '贬值；轻视', examples: [{ en: 'The currency has depreciated significantly.', zh: '货币大幅贬值。' }] }] },
  { word: 'detrimental', phonetic: '/ˌdetrɪˈmentl/', definitions: [{ pos: 'adj.', meaning: '有害的', examples: [{ en: 'Smoking is detrimental to health.', zh: '吸烟对健康有害。' }] }] },
  { word: 'deviate', phonetic: '/ˈdiːvieɪt/', definitions: [{ pos: 'v.', meaning: '偏离；背离', examples: [{ en: 'He deviated from the original plan.', zh: '他偏离了原计划。' }] }] },
  { word: 'discrepancy', phonetic: '/dɪˈskrepənsi/', definitions: [{ pos: 'n.', meaning: '差异；不一致', examples: [{ en: 'There was a discrepancy between the two reports.', zh: '两份报告之间存在差异。' }] }] },
  { word: 'elicit', phonetic: '/ɪˈlɪsɪt/', definitions: [{ pos: 'v.', meaning: '引出；诱出', examples: [{ en: 'The question elicited a surprising response.', zh: '问题引出了令人惊讶的回答。' }] }] },
  { word: 'emanate', phonetic: '/ˈeməneɪt/', definitions: [{ pos: 'v.', meaning: '发出；散发', examples: [{ en: 'A strange smell emanated from the room.', zh: '房间散发出奇怪的气味。' }] }] },
  { word: 'embody', phonetic: '/ɪmˈbɒdi/', definitions: [{ pos: 'v.', meaning: '体现；包含', examples: [{ en: 'The building embodies the spirit of the era.', zh: '建筑体现了那个时代的精神。' }] }] },
  { word: 'encompass', phonetic: '/ɪnˈkʌmpəs/', definitions: [{ pos: 'v.', meaning: '包含；围绕', examples: [{ en: 'The course encompasses a wide range of topics.', zh: '课程涵盖广泛的主题。' }] }] },
  { word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', definitions: [{ pos: 'v.', meaning: '夸大；夸张', examples: [{ en: 'The media tends to exaggerate the problem.', zh: '媒体往往夸大问题。' }] }] },
  { word: 'exempt', phonetic: '/ɪɡˈzempt/', definitions: [{ pos: 'adj.', meaning: '免除的；豁免的', examples: [{ en: 'Students are exempt from the tax.', zh: '学生免征此税。' }] }] },
  { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', definitions: [{ pos: 'v.', meaning: '波动；变动', examples: [{ en: 'The temperature fluctuates throughout the day.', zh: '温度在一天中波动。' }] }] },
  { word: 'hamper', phonetic: '/ˈhæmpər/', definitions: [{ pos: 'v.', meaning: '妨碍；阻碍', examples: [{ en: 'Bad weather hampered the rescue effort.', zh: '恶劣天气阻碍了救援工作。' }] }] },
  { word: 'harness', phonetic: '/ˈhɑːrnɪs/', definitions: [{ pos: 'v.', meaning: '利用；驾驭', examples: [{ en: 'We must harness the power of technology.', zh: '我们必须利用技术的力量。' }] }] },
  { word: 'hinder', phonetic: '/ˈhɪndər/', definitions: [{ pos: 'v.', meaning: '阻碍；妨碍', examples: [{ en: 'Lack of resources hindered the project.', zh: '资源不足阻碍了项目。' }] }] },
  { word: 'ignite', phonetic: '/ɪɡˈnaɪt/', definitions: [{ pos: 'v.', meaning: '点燃；激发', examples: [{ en: 'The speech ignited public enthusiasm.', zh: '演讲激发了公众热情。' }] }] },
  { word: 'imperative', phonetic: '/ɪmˈperətɪv/', definitions: [{ pos: 'adj.', meaning: '迫切的；必要的', examples: [{ en: 'It is imperative to act quickly.', zh: '迫切需要快速行动。' }] }] },
  { word: 'impede', phonetic: '/ɪmˈpiːd/', definitions: [{ pos: 'v.', meaning: '阻碍；妨碍', examples: [{ en: 'Snow impeded the progress of the expedition.', zh: '大雪阻碍了探险的进展。' }] }] },
  { word: 'incur', phonetic: '/ɪnˈkɜːr/', definitions: [{ pos: 'v.', meaning: '招致；引起', examples: [{ en: 'The project incurred significant costs.', zh: '项目产生了重大成本。' }] }] },
  { word: 'indulge', phonetic: '/ɪnˈdʌldʒ/', definitions: [{ pos: 'v.', meaning: '放纵；沉迷', examples: [{ en: 'She indulged in a piece of chocolate cake.', zh: '她放纵自己吃了一块巧克力蛋糕。' }] }] },
  { word: 'inflict', phonetic: '/ɪnˈflɪkt/', definitions: [{ pos: 'v.', meaning: '施加；使遭受', examples: [{ en: 'The storm inflicted heavy damage.', zh: '暴风雨造成了严重破坏。' }] }] },
  { word: 'inherent', phonetic: '/ɪnˈhɪərənt/', definitions: [{ pos: 'adj.', meaning: '固有的；内在的', examples: [{ en: 'There are inherent risks in the procedure.', zh: '该过程存在固有风险。' }] }] },
  { word: 'manifest', phonetic: '/ˈmænɪfest/', definitions: [{ pos: 'v.', meaning: '表明；显示', examples: [{ en: 'The symptoms manifest within two days.', zh: '症状在两天内显现。' }] }] },
  { word: 'mitigate', phonetic: '/ˈmɪtɪɡeɪt/', definitions: [{ pos: 'v.', meaning: '减轻；缓和', examples: [{ en: 'Steps were taken to mitigate the damage.', zh: '采取了措施来减轻损害。' }] }] },
  { word: 'nurture', phonetic: '/ˈnɜːrtʃər/', definitions: [{ pos: 'v.', meaning: '培养；养育', examples: [{ en: 'Parents should nurture their children\'s talents.', zh: '父母应该培养孩子的才能。' }] }] },
  { word: 'obstruct', phonetic: '/əbˈstrʌkt/', definitions: [{ pos: 'v.', meaning: '阻碍；妨碍', examples: [{ en: 'The fallen tree obstructed the road.', zh: '倒下的树挡住了路。' }] }] },
  { word: 'perpetuate', phonetic: '/pərˈpetʃueɪt/', definitions: [{ pos: 'v.', meaning: '使永存；使持续', examples: [{ en: 'The law perpetuates inequality.', zh: '法律使不平等持续存在。' }] }] },
  { word: 'pertain', phonetic: '/pərˈteɪn/', definitions: [{ pos: 'v.', meaning: '属于；关于', examples: [{ en: 'The information pertains to the case.', zh: '信息与案件有关。' }] }] },
  { word: 'preclude', phonetic: '/prɪˈkluːd/', definitions: [{ pos: 'v.', meaning: '排除；阻止', examples: [{ en: 'His injury precluded him from playing.', zh: '他的伤使他无法参赛。' }] }] },
  { word: 'predicament', phonetic: '/prɪˈdɪkəmənt/', definitions: [{ pos: 'n.', meaning: '困境；窘况', examples: [{ en: 'She found herself in a difficult predicament.', zh: '她发现自己陷入了困境。' }] }] },
  { word: 'profound', phonetic: '/prəˈfaʊnd/', definitions: [{ pos: 'adj.', meaning: '深刻的；深远的', examples: [{ en: 'The experience had a profound effect on him.', zh: '这段经历对他影响深远。' }] }] },
  { word: 'reconcile', phonetic: '/ˈrekənsaɪl/', definitions: [{ pos: 'v.', meaning: '调和；和解', examples: [{ en: 'It is hard to reconcile the two viewpoints.', zh: '很难调和两种观点。' }] }] },
  { word: 'relinquish', phonetic: '/rɪˈlɪŋkwɪʃ/', definitions: [{ pos: 'v.', meaning: '放弃；交出', examples: [{ en: 'He was forced to relinquish control.', zh: '他被迫放弃控制权。' }] }] },
  { word: 'repercussion', phonetic: '/ˌriːpərˈkʌʃn/', definitions: [{ pos: 'n.', meaning: '反响；后果', examples: [{ en: 'The decision had serious repercussions.', zh: '决定产生了严重后果。' }] }] },
  { word: 'scrutinize', phonetic: '/ˈskruːtənaɪz/', definitions: [{ pos: 'v.', meaning: '仔细检查', examples: [{ en: 'The committee scrutinized the proposal.', zh: '委员会仔细审查了提案。' }] }] },
  { word: 'stipulate', phonetic: '/ˈstɪpjuleɪt/', definitions: [{ pos: 'v.', meaning: '规定；约定', examples: [{ en: 'The contract stipulates a completion date.', zh: '合同规定了完成日期。' }] }] },
  { word: 'substantiate', phonetic: '/səbˈstænʃieɪt/', definitions: [{ pos: 'v.', meaning: '证实；证明', examples: [{ en: 'Can you substantiate your claims?', zh: '你能证实你的说法吗？' }] }] },
  { word: 'supersede', phonetic: '/ˌsuːpərˈsiːd/', definitions: [{ pos: 'v.', meaning: '取代；替代', examples: [{ en: 'The new law supersedes the old one.', zh: '新法律取代了旧法律。' }] }] },
  { word: 'suppress', phonetic: '/səˈpres/', definitions: [{ pos: 'v.', meaning: '压制；抑制', examples: [{ en: 'The government suppressed the rebellion.', zh: '政府镇压了叛乱。' }] }] },
  { word: 'tangible', phonetic: '/ˈtændʒəbl/', definitions: [{ pos: 'adj.', meaning: '有形的；切实的', examples: [{ en: 'We need tangible results.', zh: '我们需要切实的成果。' }] }] },
  { word: 'testify', phonetic: '/ˈtestɪfaɪ/', definitions: [{ pos: 'v.', meaning: '作证；证明', examples: [{ en: 'She testified in court.', zh: '她在法庭上作证。' }] }] },
  { word: 'undermine', phonetic: '/ˌʌndərˈmaɪn/', definitions: [{ pos: 'v.', meaning: '破坏；削弱', examples: [{ en: 'Rumors can undermine public trust.', zh: '谣言会削弱公众信任。' }] }] },
  { word: 'unprecedented', phonetic: '/ʌnˈpresɪdentɪd/', definitions: [{ pos: 'adj.', meaning: '史无前例的', examples: [{ en: 'The event was unprecedented in history.', zh: '这一事件在历史上是史无前例的。' }] }] },
  { word: 'uphold', phonetic: '/ʌpˈhəʊld/', definitions: [{ pos: 'v.', meaning: '支持；维护', examples: [{ en: 'The court upheld the original decision.', zh: '法院维持了原判。' }] }] },
  { word: 'venture', phonetic: '/ˈventʃər/', definitions: [{ pos: 'n.', meaning: '冒险；企业', examples: [{ en: 'The joint venture was successful.', zh: '合资企业取得了成功。' }] }] },
  { word: 'warrant', phonetic: '/ˈwɒrənt/', definitions: [{ pos: 'v.', meaning: '保证；使正当', examples: [{ en: 'The situation warrants careful attention.', zh: '这种情况需要仔细关注。' }] }] },
];
